# Generated by Django 3.1.4 on 2021-06-08 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_category_organiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='organiation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.userprofile'),
        ),
    ]
